#!/usr/bin/env bash
# cp -rf ./lib/node.js ./node.js
# cp -rf ./lib/node.d.ts ./node.d.ts
# cp -rf ./lib/node.js.map ./node.js.map

# cp -rf ./lib/browser.js ./browser.js
# cp -rf ./lib/browser.d.ts ./browser.d.ts
# cp -rf ./lib/browser.js.map ./browser.js.map

# cp -rf ./lib/shared.js ./shared.js
# cp -rf ./lib/shared.d.ts ./shared.d.ts
# cp -rf ./lib/shared.js.map ./shared.js.map
